server:
  port: 8080  # Spring boot Server port

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://moabuza.cyvpzdbrywmx.ap-northeast-2.rds.amazonaws.com/moabuzaDB
    username: admin
    password: moabuza123

  reids:
    host: #여기 부분은 자신의 ip에 맞춰서 바꾸기 -> ec2 redis 설치 후 연결 ip
      127.0.0.1
    port:
      6379

  jpa:
    hibernate:
      ddl-auto: update

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /log/abc.log
  level:
    root: error




jwt:
  secret: abwieineprmdspowejropsadasdasdasdvsddvsdvasd